config/routes.rb
OpenMarketMock::Application.routes.draw do

  resources :sms
  resources :phones do
    member do
      put :clear_messages
    end
    resources :messages, only: [:create]
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  validates :phone_number, presence: true, format: {with: /\A1\d{10,10}\z/, message: 'must start with a 1 and have 11 digits'}
  validates :phone_carrier, presence: true, format: {with: /\A\d\d\z/, message: 'must be two digits'}

  has_many :messages
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @message = Message.new(:phone => @phone)
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  def clear_messages
    @phone = Phone.find(params[:id])
    @phone.messages.destroy_all
    redirect_to @phone
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phone }
      else
        format.html { render action: 'new' }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:phone_number, :phone_carrier, :notes)
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :phone_carrier %><br>
    <%= f.text_field :phone_carrier %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, cols: 80, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <thead>
    <tr>
      <th>Phone number</th>
      <th>Phone carrier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.phone_number %></td>
        <td><%= phone.phone_carrier %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @phone.phone_number %>
</p>

<p>
  <strong>Phone carrier:</strong>
  <%= @phone.phone_carrier %>
</p>

<% if @phone.notes.present? %>
  <p>
    <strong>Notes:</strong>
    <%= @phone.notes %>
  </p>
<% end %>

<%= link_to "clear messages", clear_messages_phone_path(@phone), method: 'put' %>

<table>
  <% @phone.messages.each do |message| %>
    <tr>
      <td><%= message.created_at %></td>
      <% if message.source == "local" %>
        <td> --&gt; </td>
      <% else %>
        <td> &lt;-- </td>
      <% end %>
      <td><%= message.content %></td>
    </tr>
  <% end %>
</table>

<p>Enter message to send</p>

<%= form_for [@phone, @message] do |f| %>
  <div>
    <%= f.text_area :content, rows: 3, cols: 40 %>
  </div>
  <div>
    <%= label_tag 'Attachment:' %>
    <%= select_tag 'image', options_for_select(['', 'flower-tiny.jpg', 'adam.jpg', 'sample.mov']) %>
  </div>
  <hr/>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>